### ISSUE TITLE
Network interface settings break networking

### ISSUE THREAD

**Issue by shb** [FABtotum/colibri-fabui#4]
New network configuration code from 0.9 produces defective `/etc/network/interfaces`.

The problem seems related to the wifi interface not being enabled.

Also, in colibri, any `allow-hotplug` directive must precede the `auto` directive for the corresponding interface.

**Comment by infinity0n3** [comment]
The problems is that the attribute wireless-essid in /etc/network/interfaces is empty.
This is a syntax error and there fore ifup stops and no interfaces are brought up. The solution is to use [wireless-essid ""] if there is no essid configured.

**Comment by shb** [comment]
Closed in 228fe47df60b3a47e61c8d178634a6ebd75ea812
